#ifndef VESTIGE_CORE_DEFINES_H
#define VESTIGE_CORE_DEFINES_H

#define VESTIGE_CORE_VECTOR_INTEGRITY_CHECK
#ifdef VESTIGE_CORE_VECTOR_INTEGRITY_CHECK
#define VESTIGE_CORE_VECTOR_INITIALIED_KEY (0xA1)
#endif

#define VESTIGE_CORE_HASHMAP_INTEGRITY_CHECK
#ifdef VESTIGE_CORE_HASHMAP_INTEGRITY_CHECK
#define VESTIGE_CORE_HASHMAP_INITIALIED_KEY (0xB1)
#define VESTIGE_CORE_HASHMAP_BUCKET_INITIALIED_KEY (0xC1)
#endif

#endif
