#ifndef VESTIGE_CORE_DEFINES_H
#define VESTIGE_CORE_DEFINES_H

#define VESTIGE_CORE_VECTOR_INTEGRITY_CHECK
#ifdef VESTIGE_CORE_VECTOR_INTEGRITY_CHECK
#define VESTIGE_CORE_VECTOR_INITIALIED_KEY (0xA1)
#endif

#endif
