#ifndef VESTIGE_ANCHOR_H
#define VESTIGE_ANCHOR_H

typedef enum Anchor {
    ANCHOR_TOP_LEFT,
    ANCHOR_TOP_MIDDLE,
    ANCHOR_TOP_RIGHT,
    ANCHOR_MIDDLE_LEFT,
    ANCHOR_MIDDLE,
    ANCHOR_MIDDLE_RIGHT,
    ANCHOR_BOTTOM_LEFT,
    ANCHOR_BOTTOM_MIDDLE,
    ANCHOR_BOTTOM_RIGHT
} Anchor;

#endif
